### ISSUE TITLE
ERR_SSL_VERSION_OR_CIPHER_MISMATCH on Amazon Linux

### ISSUE THREAD

**Issue by ogis-onishi** [typesafehub/activator-play-tls-example#4]
When I run this example on Amazon Linux, I get the following errors.
* "ERR_SSL_VERSION_OR_CIPHER_MISMATCH" on Chrome 48
* "ssl_error_no_cypher_overlap" on Firefox 44.0.2

How can I fix this issue?
This works on my local machine. Is this Java configuration issue?

Here is my code:
https://github.com/ogis-onishi/activator-play-tls-example

And the details of my questions is as follows.
http://stackoverflow.com/questions/35598266/play-scala-err-ssl-version-or-cipher-mismatch

**Comment by ogis-onishi** [comment]
@wsargent 
Could you take a look?

**Comment by wsargent** [comment]
This is an HTTP configuration issue -- take out all the explicit version and cipher configuration and turn on the debugging options https://www.playframework.com/documentation/2.4.x/DebuggingSSL

**Comment by vwhoho** [comment]
I want to use the CustomSSLEngineProvider in Play to do 2-way SSL. Even though needClientAuth=true, the server does not request the client to send its certificate. 

Details follow:
1) I use self sign server and client certificates
2) I perform https on Chrome to hit the site. It said connection is not private but I chose Advanced to proceed 
3) Then I got the content immediately from the server 

Step 3) shouldn't just happen because the server is expected to request a certificate from the client and Chrome will prompt me to send a certificate. But that didn't happen

Can you give me any clue why?

**Comment by wsargent** [comment]
@vwhoho you should turn on the debugging options so you can see what's going on.

Make sure you are running ./play with the following option enabled:

https://github.com/playframework/play-scala-tls-example/blob/2.6.x/play#L24

and you should check that needClientAuth is true in the code:

https://github.com/playframework/play-scala-tls-example/blob/2.6.x/app/https/CustomSSLEngineProvider.scala#L92
